DROP TABLE IF EXISTS ALBUMS;
DROP TABLE IF EXISTS ARTISTS;

CREATE TABLE ARTISTS(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE ALBUMS(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  style VARCHAR(255),
  artist_id INT REFERENCES artists(id)
);
